package com.myhcl.security.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.myhcl.security.entity.User;
import com.myhcl.security.entity.UserRequest;
import com.myhcl.security.entity.UserResponse;
import com.myhcl.security.service.IUserService;
import com.myhcl.security.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {
	
	@Autowired
	private IUserService userService;
	@Autowired
	private AuthenticationManager authManager;
	@Autowired
	private JwtUtil jwtUtil;
	
	@PostMapping("/register")
	public ResponseEntity<String> register(@RequestBody User user){
		Long id=userService.saveUser(user);
		return new ResponseEntity<String>("User "+id+" saved", HttpStatus.CREATED);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> login(@RequestBody UserRequest request){
		UsernamePasswordAuthenticationToken token=
				               new UsernamePasswordAuthenticationToken(request.getEmail(),
				            		                                                                                   request.getPassword());
		authManager.authenticate(token);
		String jwtToken=jwtUtil.generateToken(request.getEmail());
		return new ResponseEntity<UserResponse>(new UserResponse(jwtToken,"Success! Generated By Sandeep Verma"),
                                                                                                 HttpStatus.OK
                                                                                               );
	}
	
	@GetMapping("/welcome")
	public ResponseEntity<String> welcomeMsg(Principal principal){
		return new ResponseEntity<String>("Welcome "+principal.getName(), HttpStatus.OK);
	}

}
